name: Docker Publish

on:
  push:
    paths-ignore:
      - 'README.md'
      - '**.png'
  pull_request:
    paths-ignore:
      - 'README.md'
      - '**.png'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Convert repository name to lowercase
      run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          docker.io/${{ env.REPO_NAME }}
          ghcr.io/${{ env.REPO_NAME }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=ref,event=branch
          type=ref,event=pr
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
          type=sha

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        provenance: false
        platforms: linux/amd64,linux/arm64/v8
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Generate artifact attestation for GHCR
      if: ${{ github.event.repository.visibility == 'public' && github.event_name != 'pull_request' }}
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ghcr.io/${{ env.REPO_NAME }}
        subject-digest: ${{ steps.build-and-push.outputs.digest }}
        push-to-registry: true

    - name: Generate artifact attestation for Docker Hub
      if: ${{ github.event.repository.visibility == 'public' && github.event_name != 'pull_request' }}
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: docker.io/${{ env.REPO_NAME }}
        subject-digest: ${{ steps.build-and-push.outputs.digest }}
        push-to-registry: true