name: Update Docker Hub Description

on:
  push:
    branches: [ master ]
    paths:
      - 'README.md'

jobs:
  update-description:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Convert repository name to lowercase
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@e98e4d1628a5f3be2be7c231e50981aee98723ae
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.REPO_NAME }}
          enable-url-completion: true